
[Entrada]
salariobruto = 12000.00

[Impostos]
simples = 0.06

[PF]
dependentes = 1

[Obrigacoes]
prolabore = 8157.41
fgts = 0.08
ferias = 0.09
adicionalferias = 0.03
decimoterceiro = 0.09

[Reservas]
emergencia = 1000

[Beneficios] 
ValeRefeicao = 1000
PlanoSaude = 1500
	